kafka-conf:
  server: localhost:9092

app:
  #  cron: 20 0/3 * * * * # an event occurs every 3 minutes at the 20th second
  #  cron: 20 0/1 * * * * # an event occurs every minute at the 20th second
  cron: 0/15 * * * * * # an event occurs every 15 seconds
#  cron: 0/5 * * * * * # an event occurs every 5 seconds

server:
  port: 8091

management:
  endpoint:
    health:
      show-components: always
      show-details: always

spring:
  kafka:
    bootstrap-servers: ${kafka-conf.server}
    producer:
      transactions: true
      bootstrap-servers: ${kafka-conf.server}
    consumer:
      group-id: ${kafka-conf.group-id}
      auto-offset-reset: earliest
      enable-auto-commit: true
      bootstrap-servers: ${kafka-conf.server}
      properties:
        isolation.level: read_committed
        max.poll.interval.ms: 3000
    admin:
      fail-fast: true
#    properties:
#      acks: all
#      retries: 2
#    transactions:
#      transaction-id-prefix: transaction-id-prefix
